# Generated by Django 6.1 on 2026-09-18 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_category_image'),
    ]

    operations = [
        migrations.RenameField(
        model_name="category",
        old_name="name",
        new_name="name_en",
        ),
    migrations.RenameField(
        model_name="question",
        old_name="text",
        new_name="text_en",
        ),
    migrations.RenameField(
        model_name="question",
        old_name="explanation",
        new_name="explanation_en",
        ),
    migrations.RenameField(
        model_name="answer",
        old_name="text",
        new_name="text_en",
        ),
    ]
