# Generated by Django 6.1 on 2026-09-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_rename_fields_for_english'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='text_ro',
            field=models.CharField(default='', max_length=255, verbose_name='Answer (Romanian)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='name_ro',
            field=models.CharField(default='', max_length=100, verbose_name='Category (Romanian)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='explanation_ro',
            field=models.TextField(default='', verbose_name='Explanation (Romanian)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='text_ro',
            field=models.TextField(default='', verbose_name='Question (Romanian)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='text_en',
            field=models.CharField(max_length=255, verbose_name='Answer (English)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=100, verbose_name='Category (English)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation_en',
            field=models.TextField(verbose_name='Explanation (English)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text_en',
            field=models.TextField(verbose_name='Question (English)'),
        ),
    ]
